import sys
lines = []
def w(s): lines.append(s)

w(chr(34)*3)
w("Interactive Podcast Studio - EdgeTTS + OpenRouter AI")
w(chr(34)*3)
w("")
w("import re, os, json, time, asyncio, queue, threading")
w("from pathlib import Path")
w("from datetime import datetime")
w("from concurrent.futures import ThreadPoolExecutor, as_completed")
w("from flask import Flask, render_template, request, jsonify, send_file, Response")
w("import edge_tts")
w("from openai import OpenAI")
w("")
w("try:")
w("    import fitz")
w("    PDF_SUPPORT = True")
w("except ImportError:")
w("    PDF_SUPPORT = False")
w("")
w("try:")
w("    import docx")
w("    DOCX_SUPPORT = True")
w("except ImportError:")
w("    DOCX_SUPPORT = False")
w("")
w("try:")
w("    import wikipedia")
w("    WIKI_SUPPORT = True")
w("except ImportError:")
w("    WIKI_SUPPORT = False")
w("")
w("OPENROUTER_API_KEY = chr(34) + chr(115) + chr(107) + chr(45) + chr(111) + chr(114) + chr(45) + chr(118) + chr(49) + chr(45) + chr(99) + chr(51) + chr(52) + chr(56) + chr(51) + chr(55) + chr(54) + chr(99) + chr(49) + chr(55) + chr(52) + chr(53) + chr(53) + chr(50) + chr(98) + chr(55) + chr(99) + chr(48) + chr(52) + chr(99) + chr(102) + chr(53) + chr(51) + chr(97) + chr(54) + chr(102) + chr(100) + chr(50) + chr(57) + chr(54) + chr(55) + chr(98) + chr(52) + chr(57) + chr(48) + chr(57) + chr(53) + chr(100) + chr(54) + chr(101) + chr(100) + chr(50) + chr(57) + chr(100) + chr(57) + chr(99) + chr(97) + chr(99) + chr(52) + chr(53) + chr(54) + chr(56) + chr(101) + chr(49) + chr(54) + chr(99) + chr(97) + chr(97) + chr(57) + chr(55) + chr(49) + chr(57) + chr(55) + chr(34)")
open("interactive_podcast_studio.py","w",encoding="utf-8").write("\n".join(lines))
print("done", len(lines))
