import base64

lines = []
A = lines.append

# LANGUAGE VOICES
A("LANGUAGE_VOICES = {")
A('    "english": [')
A('        {"voice": "en-US-GuyNeural",   "name": "Guy (US Male)"},')
A('        {"voice": "en-US-JennyNeural", "name": "Jenny (US Female)"},')
A('        {"voice": "en-GB-RyanNeural",  "name": "Ryan (UK Male)"},')
A('        {"voice": "en-GB-SoniaNeural", "name": "Sonia (UK Female)"},')
A("    ],")
A('    "hinglish": [')
A('        {"voice": "en-IN-PrabhatNeural", "name": "Prabhat (Indian Male)"},')
A('        {"voice": "en-IN-NeerjaNeural",  "name": "Neerja (Indian Female)"},')
A('        {"voice": "hi-IN-MadhurNeural",  "name": "Madhur (Hindi Male)"},')
A('        {"voice": "hi-IN-SwaraNeural",   "name": "Swara (Hindi Female)"},')
A("    ],")
A('    "hindi": [')
A('        {"voice": "hi-IN-MadhurNeural", "name": "Madhur (Hindi Male)"},')
A('        {"voice": "hi-IN-SwaraNeural",  "name": "Swara (Hindi Female)"},')
A('        {"voice": "hi-IN-MadhurNeural", "name": "Madhur (Hindi Male)"},')
A('        {"voice": "hi-IN-SwaraNeural",  "name": "Swara (Hindi Female)"},')
A("    ],")
A('    "spanish": [{"voice": "es-ES-AlvaroNeural","name": "Alvaro (Spain Male)"},{"voice": "es-ES-ElviraNeural","name": "Elvira (Spain Female)"},{"voice": "es-MX-JorgeNeural","name": "Jorge (Mexico Male)"},{"voice": "es-MX-DaliaNeural","name": "Dalia (Mexico Female)"}],')
A('    "french":  [{"voice": "fr-FR-HenriNeural","name": "Henri (France Male)"},{"voice": "fr-FR-DeniseNeural","name": "Denise (France Female)"},{"voice": "fr-CA-ThierryNeural","name": "Thierry (Canada Male)"},{"voice": "fr-CA-SylvieNeural","name": "Sylvie (Canada Female)"}],')
A('    "german":  [{"voice": "de-DE-FlorianMultilingualNeural","name": "Florian (Germany Male)"},{"voice": "de-DE-SeraphinaMultilingualNeural","name": "Seraphina (Germany Female)"},{"voice": "de-AT-JonasNeural","name": "Jonas (Austria Male)"},{"voice": "de-AT-IngridNeural","name": "Ingrid (Austria Female)"}],')
A('    "japanese":[{"voice": "ja-JP-KeitaNeural","name": "Keita (Japan Male)"},{"voice": "ja-JP-NanamiNeural","name": "Nanami (Japan Female)"},{"voice": "ja-JP-KeitaNeural","name": "Keita (Japan Male)"},{"voice": "ja-JP-NanamiNeural","name": "Nanami (Japan Female)"}],')
A('    "arabic":  [{"voice": "ar-SA-HamedNeural","name": "Hamed (Saudi Male)"},{"voice": "ar-SA-ZariyahNeural","name": "Zariyah (Saudi Female)"},{"voice": "ar-EG-ShakirNeural","name": "Shakir (Egypt Male)"},{"voice": "ar-EG-SalmaNeural","name": "Salma (Egypt Female)"}],')
A('    "chinese": [{"voice": "zh-CN-YunjianNeural","name": "Yunjian (China Male)"},{"voice": "zh-CN-XiaoxiaoNeural","name": "Xiaoxiao (China Female)"},{"voice": "zh-TW-YunJheNeural","name": "YunJhe (Taiwan Male)"},{"voice": "zh-TW-HsiaoChenNeural","name": "HsiaoChen (Taiwan Female)"}],')
A('    "portuguese":[{"voice": "pt-BR-AntonioNeural","name": "Antonio (Brazil Male)"},{"voice": "pt-BR-ThalitaMultilingualNeural","name": "Thalita (Brazil Female)"},{"voice": "pt-PT-DuarteNeural","name": "Duarte (Portugal Male)"},{"voice": "pt-PT-RaquelNeural","name": "Raquel (Portugal Female)"}],')
A('    "russian": [{"voice": "ru-RU-DmitryNeural","name": "Dmitry (Russia Male)"},{"voice": "ru-RU-SvetlanaNeural","name": "Svetlana (Russia Female)"},{"voice": "ru-RU-DmitryNeural","name": "Dmitry (Russia Male)"},{"voice": "ru-RU-SvetlanaNeural","name": "Svetlana (Russia Female)"}],')
A('    "korean":  [{"voice": "ko-KR-InJoonNeural","name": "InJoon (Korea Male)"},{"voice": "ko-KR-SunHiNeural","name": "SunHi (Korea Female)"},{"voice": "ko-KR-HyunsuMultilingualNeural","name": "Hyunsu (Korea Male)"},{"voice": "ko-KR-SunHiNeural","name": "SunHi (Korea Female)"}],')
A('    "italian": [{"voice": "it-IT-GiuseppeMultilingualNeural","name": "Giuseppe (Italy Male)"},{"voice": "it-IT-ElsaNeural","name": "Elsa (Italy Female)"},{"voice": "it-IT-DiegoNeural","name": "Diego (Italy Male)"},{"voice": "it-IT-IsabellaNeural","name": "Isabella (Italy Female)"}],')
A('    "turkish": [{"voice": "tr-TR-AhmetNeural","name": "Ahmet (Turkey Male)"},{"voice": "tr-TR-EmelNeural","name": "Emel (Turkey Female)"},{"voice": "tr-TR-AhmetNeural","name": "Ahmet (Turkey Male)"},{"voice": "tr-TR-EmelNeural","name": "Emel (Turkey Female)"}],')
A('    "dutch":   [{"voice": "nl-NL-MaartenNeural","name": "Maarten (Netherlands Male)"},{"voice": "nl-NL-ColetteNeural","name": "Colette (Netherlands Female)"},{"voice": "nl-BE-ArnaudNeural","name": "Arnaud (Belgium Male)"},{"voice": "nl-BE-DenaNeural","name": "Dena (Belgium Female)"}],')
A('    "polish":  [{"voice": "pl-PL-MarekNeural","name": "Marek (Poland Male)"},{"voice": "pl-PL-ZofiaNeural","name": "Zofia (Poland Female)"},{"voice": "pl-PL-MarekNeural","name": "Marek (Poland Male)"},{"voice": "pl-PL-ZofiaNeural","name": "Zofia (Poland Female)"}],')
A('    "swedish": [{"voice": "sv-SE-MattiasNeural","name": "Mattias (Sweden Male)"},{"voice": "sv-SE-SofieNeural","name": "Sofie (Sweden Female)"},{"voice": "sv-SE-MattiasNeural","name": "Mattias (Sweden Male)"},{"voice": "sv-SE-SofieNeural","name": "Sofie (Sweden Female)"}],')
A('    "indonesian":[{"voice": "id-ID-ArdiNeural","name": "Ardi (Indonesia Male)"},{"voice": "id-ID-GadisNeural","name": "Gadis (Indonesia Female)"},{"voice": "id-ID-ArdiNeural","name": "Ardi (Indonesia Male)"},{"voice": "id-ID-GadisNeural","name": "Gadis (Indonesia Female)"}],')
A('    "tamil":   [{"voice": "ta-IN-ValluvarNeural","name": "Valluvar (Tamil Male)"},{"voice": "ta-IN-PallaviNeural","name": "Pallavi (Tamil Female)"},{"voice": "ta-MY-SuryaNeural","name": "Surya (Malaysia Male)"},{"voice": "ta-MY-KaniNeural","name": "Kani (Malaysia Female)"}],')
A('    "bengali": [{"voice": "bn-IN-BashkarNeural","name": "Bashkar (India Male)"},{"voice": "bn-IN-TanishaaNeural","name": "Tanishaa (India Female)"},{"voice": "bn-BD-PradeepNeural","name": "Pradeep (Bangladesh Male)"},{"voice": "bn-BD-NabanitaNeural","name": "Nabanita (Bangladesh Female)"}],')
A('    "urdu":    [{"voice": "ur-PK-AsadNeural","name": "Asad (Pakistan Male)"},{"voice": "ur-PK-UzmaNeural","name": "Uzma (Pakistan Female)"},{"voice": "ur-IN-SalmanNeural","name": "Salman (India Male)"},{"voice": "ur-IN-GulNeural","name": "Gul (India Female)"}],')
A('    "telugu":  [{"voice": "te-IN-MohanNeural","name": "Mohan (Telugu Male)"},{"voice": "te-IN-ShrutiNeural","name": "Shruti (Telugu Female)"},{"voice": "te-IN-MohanNeural","name": "Mohan (Telugu Male)"},{"voice": "te-IN-ShrutiNeural","name": "Shruti (Telugu Female)"}],')
A('    "marathi": [{"voice": "mr-IN-ManoharNeural","name": "Manohar (Marathi Male)"},{"voice": "mr-IN-AarohiNeural","name": "Aarohi (Marathi Female)"},{"voice": "mr-IN-ManoharNeural","name": "Manohar (Marathi Male)"},{"voice": "mr-IN-AarohiNeural","name": "Aarohi (Marathi Female)"}],')
A('    "gujarati":[{"voice": "gu-IN-NiranjanNeural","name": "Niranjan (Gujarati Male)"},{"voice": "gu-IN-DhwaniNeural","name": "Dhwani (Gujarati Female)"},{"voice": "gu-IN-NiranjanNeural","name": "Niranjan (Gujarati Male)"},{"voice": "gu-IN-DhwaniNeural","name": "Dhwani (Gujarati Female)"}],')
A('    "kannada": [{"voice": "kn-IN-GaganNeural","name": "Gagan (Kannada Male)"},{"voice": "kn-IN-SapnaNeural","name": "Sapna (Kannada Female)"},{"voice": "kn-IN-GaganNeural","name": "Gagan (Kannada Male)"},{"voice": "kn-IN-SapnaNeural","name": "Sapna (Kannada Female)"}],')
A('    "malayalam":[{"voice": "ml-IN-MidhunNeural","name": "Midhun (Malayalam Male)"},{"voice": "ml-IN-SobhanaNeural","name": "Sobhana (Malayalam Female)"},{"voice": "ml-IN-MidhunNeural","name": "Midhun (Malayalam Male)"},{"voice": "ml-IN-SobhanaNeural","name": "Sobhana (Malayalam Female)"}],')
A('    "nepali":  [{"voice": "ne-NP-SagarNeural","name": "Sagar (Nepali Male)"},{"voice": "ne-NP-HemkalaNeural","name": "Hemkala (Nepali Female)"},{"voice": "ne-NP-SagarNeural","name": "Sagar (Nepali Male)"},{"voice": "ne-NP-HemkalaNeural","name": "Hemkala (Nepali Female)"}],')
A('    "sinhala": [{"voice": "si-LK-SameeraNeural","name": "Sameera (Sinhala Male)"},{"voice": "si-LK-ThiliniNeural","name": "Thilini (Sinhala Female)"},{"voice": "si-LK-SameeraNeural","name": "Sameera (Sinhala Male)"},{"voice": "si-LK-ThiliniNeural","name": "Thilini (Sinhala Female)"}],')
A('    "malay":   [{"voice": "ms-MY-OsmanNeural","name": "Osman (Malay Male)"},{"voice": "ms-MY-YasminNeural","name": "Yasmin (Malay Female)"},{"voice": "ms-MY-OsmanNeural","name": "Osman (Malay Male)"},{"voice": "ms-MY-YasminNeural","name": "Yasmin (Malay Female)"}],')
A('    "vietnamese":[{"voice": "vi-VN-NamMinhNeural","name": "NamMinh (Vietnamese Male)"},{"voice": "vi-VN-HoaiMyNeural","name": "HoaiMy (Vietnamese Female)"},{"voice": "vi-VN-NamMinhNeural","name": "NamMinh (Vietnamese Male)"},{"voice": "vi-VN-HoaiMyNeural","name": "HoaiMy (Vietnamese Female)"}],')
A('    "thai":    [{"voice": "th-TH-NiwatNeural","name": "Niwat (Thai Male)"},{"voice": "th-TH-PremwadeeNeural","name": "Premwadee (Thai Female)"},{"voice": "th-TH-NiwatNeural","name": "Niwat (Thai Male)"},{"voice": "th-TH-PremwadeeNeural","name": "Premwadee (Thai Female)"}],')
A('    "filipino":[{"voice": "fil-PH-AngeloNeural","name": "Angelo (Filipino Male)"},{"voice": "fil-PH-BlessicaNeural","name": "Blessica (Filipino Female)"},{"voice": "fil-PH-AngeloNeural","name": "Angelo (Filipino Male)"},{"voice": "fil-PH-BlessicaNeural","name": "Blessica (Filipino Female)"}],')
A('    "greek":   [{"voice": "el-GR-NestorasNeural","name": "Nestoras (Greek Male)"},{"voice": "el-GR-AthinaNeural","name": "Athina (Greek Female)"},{"voice": "el-GR-NestorasNeural","name": "Nestoras (Greek Male)"},{"voice": "el-GR-AthinaNeural","name": "Athina (Greek Female)"}],')
A('    "czech":   [{"voice": "cs-CZ-AntoninNeural","name": "Antonin (Czech Male)"},{"voice": "cs-CZ-VlastaNeural","name": "Vlasta (Czech Female)"},{"voice": "cs-CZ-AntoninNeural","name": "Antonin (Czech Male)"},{"voice": "cs-CZ-VlastaNeural","name": "Vlasta (Czech Female)"}],')
A('    "romanian":[{"voice": "ro-RO-EmilNeural","name": "Emil (Romanian Male)"},{"voice": "ro-RO-AlinaNeural","name": "Alina (Romanian Female)"},{"voice": "ro-RO-EmilNeural","name": "Emil (Romanian Male)"},{"voice": "ro-RO-AlinaNeural","name": "Alina (Romanian Female)"}],')
A('    "hungarian":[{"voice": "hu-HU-TamasNeural","name": "Tamas (Hungarian Male)"},{"voice": "hu-HU-NoemiNeural","name": "Noemi (Hungarian Female)"},{"voice": "hu-HU-TamasNeural","name": "Tamas (Hungarian Male)"},{"voice": "hu-HU-NoemiNeural","name": "Noemi (Hungarian Female)"}],')
A('    "danish":  [{"voice": "da-DK-JeppeNeural","name": "Jeppe (Danish Male)"},{"voice": "da-DK-ChristelNeural","name": "Christel (Danish Female)"},{"voice": "da-DK-JeppeNeural","name": "Jeppe (Danish Male)"},{"voice": "da-DK-ChristelNeural","name": "Christel (Danish Female)"}],')
A('    "finnish": [{"voice": "fi-FI-HarriNeural","name": "Harri (Finnish Male)"},{"voice": "fi-FI-NooraNeural","name": "Noora (Finnish Female)"},{"voice": "fi-FI-HarriNeural","name": "Harri (Finnish Male)"},{"voice": "fi-FI-NooraNeural","name": "Noora (Finnish Female)"}],')
A('    "norwegian":[{"voice": "nb-NO-FinnNeural","name": "Finn (Norwegian Male)"},{"voice": "nb-NO-PernilleNeural","name": "Pernille (Norwegian Female)"},{"voice": "nb-NO-FinnNeural","name": "Finn (Norwegian Male)"},{"voice": "nb-NO-PernilleNeural","name": "Pernille (Norwegian Female)"}],')
A('    "ukrainian":[{"voice": "uk-UA-OstapNeural","name": "Ostap (Ukrainian Male)"},{"voice": "uk-UA-PolinaNeural","name": "Polina (Ukrainian Female)"},{"voice": "uk-UA-OstapNeural","name": "Ostap (Ukrainian Male)"},{"voice": "uk-UA-PolinaNeural","name": "Polina (Ukrainian Female)"}],')
A('    "persian": [{"voice": "fa-IR-FaridNeural","name": "Farid (Persian Male)"},{"voice": "fa-IR-DilaraNeural","name": "Dilara (Persian Female)"},{"voice": "fa-IR-FaridNeural","name": "Farid (Persian Male)"},{"voice": "fa-IR-DilaraNeural","name": "Dilara (Persian Female)"}],')
A('    "hebrew":  [{"voice": "he-IL-AvriNeural","name": "Avri (Hebrew Male)"},{"voice": "he-IL-HilaNeural","name": "Hila (Hebrew Female)"},{"voice": "he-IL-AvriNeural","name": "Avri (Hebrew Male)"},{"voice": "he-IL-HilaNeural","name": "Hila (Hebrew Female)"}],')
A('    "swahili": [{"voice": "sw-KE-RafikiNeural","name": "Rafiki (Swahili Male)"},{"voice": "sw-KE-ZuriNeural","name": "Zuri (Swahili Female)"},{"voice": "sw-KE-RafikiNeural","name": "Rafiki (Swahili Male)"},{"voice": "sw-KE-ZuriNeural","name": "Zuri (Swahili Female)"}],')
A('    "amharic": [{"voice": "am-ET-AmehaNeural","name": "Ameha (Amharic Male)"},{"voice": "am-ET-MekdesNeural","name": "Mekdes (Amharic Female)"},{"voice": "am-ET-AmehaNeural","name": "Ameha (Amharic Male)"},{"voice": "am-ET-MekdesNeural","name": "Mekdes (Amharic Female)"}],')
A('    "zulu":    [{"voice": "zu-ZA-ThembaNeural","name": "Themba (Zulu Male)"},{"voice": "zu-ZA-ThandoNeural","name": "Thando (Zulu Female)"},{"voice": "zu-ZA-ThembaNeural","name": "Themba (Zulu Male)"},{"voice": "zu-ZA-ThandoNeural","name": "Thando (Zulu Female)"}],')
A('    "afrikaans":[{"voice": "af-ZA-WillemNeural","name": "Willem (Afrikaans Male)"},{"voice": "af-ZA-AdriNeural","name": "Adri (Afrikaans Female)"},{"voice": "af-ZA-WillemNeural","name": "Willem (Afrikaans Male)"},{"voice": "af-ZA-AdriNeural","name": "Adri (Afrikaans Female)"}],')
A('    "azerbaijani":[{"voice": "az-AZ-BabekNeural","name": "Babek (Azerbaijani Male)"},{"voice": "az-AZ-BanuNeural","name": "Banu (Azerbaijani Female)"},{"voice": "az-AZ-BabekNeural","name": "Babek (Azerbaijani Male)"},{"voice": "az-AZ-BanuNeural","name": "Banu (Azerbaijani Female)"}],')
A('    "kazakh":  [{"voice": "kk-KZ-DauletNeural","name": "Daulet (Kazakh Male)"},{"voice": "kk-KZ-AigulNeural","name": "Aigul (Kazakh Female)"},{"voice": "kk-KZ-DauletNeural","name": "Daulet (Kazakh Male)"},{"voice": "kk-KZ-AigulNeural","name": "Aigul (Kazakh Female)"}],')
A('    "uzbek":   [{"voice": "uz-UZ-SardorNeural","name": "Sardor (Uzbek Male)"},{"voice": "uz-UZ-MadinaNeural","name": "Madina (Uzbek Female)"},{"voice": "uz-UZ-SardorNeural","name": "Sardor (Uzbek Male)"},{"voice": "uz-UZ-MadinaNeural","name": "Madina (Uzbek Female)"}],')
A('    "mongolian":[{"voice": "mn-MN-BataaNeural","name": "Bataa (Mongolian Male)"},{"voice": "mn-MN-YesuiNeural","name": "Yesui (Mongolian Female)"},{"voice": "mn-MN-BataaNeural","name": "Bataa (Mongolian Male)"},{"voice": "mn-MN-YesuiNeural","name": "Yesui (Mongolian Female)"}],')
A('    "burmese": [{"voice": "my-MM-ThihaNeural","name": "Thiha (Burmese Male)"},{"voice": "my-MM-NilarNeural","name": "Nilar (Burmese Female)"},{"voice": "my-MM-ThihaNeural","name": "Thiha (Burmese Male)"},{"voice": "my-MM-NilarNeural","name": "Nilar (Burmese Female)"}],')
A('    "khmer":   [{"voice": "km-KH-PisethNeural","name": "Piseth (Khmer Male)"},{"voice": "km-KH-SreymomNeural","name": "Sreymom (Khmer Female)"},{"voice": "km-KH-PisethNeural","name": "Piseth (Khmer Male)"},{"voice": "km-KH-SreymomNeural","name": "Sreymom (Khmer Female)"}],')
A('    "lao":     [{"voice": "lo-LA-ChanthavongNeural","name": "Chanthavong (Lao Male)"},{"voice": "lo-LA-KeomanyNeural","name": "Keomany (Lao Female)"},{"voice": "lo-LA-ChanthavongNeural","name": "Chanthavong (Lao Male)"},{"voice": "lo-LA-KeomanyNeural","name": "Keomany (Lao Female)"}],')
A('    "catalan": [{"voice": "ca-ES-EnricNeural","name": "Enric (Catalan Male)"},{"voice": "ca-ES-JoanaNeural","name": "Joana (Catalan Female)"},{"voice": "ca-ES-EnricNeural","name": "Enric (Catalan Male)"},{"voice": "ca-ES-JoanaNeural","name": "Joana (Catalan Female)"}],')
A('    "slovak":  [{"voice": "sk-SK-LukasNeural","name": "Lukas (Slovak Male)"},{"voice": "sk-SK-ViktoriaNeural","name": "Viktoria (Slovak Female)"},{"voice": "sk-SK-LukasNeural","name": "Lukas (Slovak Male)"},{"voice": "sk-SK-ViktoriaNeural","name": "Viktoria (Slovak Female)"}],')
A('    "croatian":[{"voice": "hr-HR-SreckoNeural","name": "Srecko (Croatian Male)"},{"voice": "hr-HR-GabrijelaNeural","name": "Gabrijela (Croatian Female)"},{"voice": "hr-HR-SreckoNeural","name": "Srecko (Croatian Male)"},{"voice": "hr-HR-GabrijelaNeural","name": "Gabrijela (Croatian Female)"}],')
A('    "bulgarian":[{"voice": "bg-BG-BorislavNeural","name": "Borislav (Bulgarian Male)"},{"voice": "bg-BG-KalinaNeural","name": "Kalina (Bulgarian Female)"},{"voice": "bg-BG-BorislavNeural","name": "Borislav (Bulgarian Male)"},{"voice": "bg-BG-KalinaNeural","name": "Kalina (Bulgarian Female)"}],')
A('    "somali":  [{"voice": "so-SO-MuuseNeural","name": "Muuse (Somali Male)"},{"voice": "so-SO-UbaxNeural","name": "Ubax (Somali Female)"},{"voice": "so-SO-MuuseNeural","name": "Muuse (Somali Male)"},{"voice": "so-SO-UbaxNeural","name": "Ubax (Somali Female)"}],')
A('    "galician":[{"voice": "gl-ES-RoiNeural","name": "Roi (Galician Male)"},{"voice": "gl-ES-SabelaNeural","name": "Sabela (Galician Female)"},{"voice": "gl-ES-RoiNeural","name": "Roi (Galician Male)"},{"voice": "gl-ES-SabelaNeural","name": "Sabela (Galician Female)"}],')
A('    "welsh":   [{"voice": "cy-GB-AledNeural","name": "Aled (Welsh Male)"},{"voice": "cy-GB-NiaNeural","name": "Nia (Welsh Female)"},{"voice": "cy-GB-AledNeural","name": "Aled (Welsh Male)"},{"voice": "cy-GB-NiaNeural","name": "Nia (Welsh Female)"}],')
A('    "irish":   [{"voice": "ga-IE-ColmNeural","name": "Colm (Irish Male)"},{"voice": "ga-IE-OrlaNeural","name": "Orla (Irish Female)"},{"voice": "ga-IE-ColmNeural","name": "Colm (Irish Male)"},{"voice": "ga-IE-OrlaNeural","name": "Orla (Irish Female)"}],')
A('    "javanese":[{"voice": "jv-ID-DimasNeural","name": "Dimas (Javanese Male)"},{"voice": "jv-ID-SitiNeural","name": "Siti (Javanese Female)"},{"voice": "jv-ID-DimasNeural","name": "Dimas (Javanese Male)"},{"voice": "jv-ID-SitiNeural","name": "Siti (Javanese Female)"}],')
A("}")
A("")
A("NON_LATIN = {")
A('    "hindi","japanese","arabic","chinese","russian","korean","tamil","bengali","urdu",')
A('    "telugu","marathi","gujarati","kannada","malayalam","nepali","sinhala","thai",')
A('    "amharic","persian","hebrew","burmese","khmer","lao","mongolian","ukrainian","bulgarian",')
A("}")
A("")
A('OUTPUT_DIR = Path("generated_podcasts")')
A('TEMP_DIR   = Path("temp_audio")')
A("OUTPUT_DIR.mkdir(exist_ok=True)")
A("TEMP_DIR.mkdir(exist_ok=True)")
A('HISTORY_FILE = OUTPUT_DIR / "history.json"')
A("")
A("app = Flask(__name__)")
A("progress_queues = {}")
A("")

code = "\n".join(lines) + "\n"
existing = open("interactive_podcast_studio.py","r",encoding="utf-8").read()
open("interactive_podcast_studio.py","w",encoding="utf-8").write(existing + code)
print("part2 ok, total:", len(existing)+len(code))