import base64

lines = []
A = lines.append

A("import re, os, json, time, asyncio, queue, threading")
A("from pathlib import Path")
A("from datetime import datetime")
A("from concurrent.futures import ThreadPoolExecutor, as_completed")
A("from flask import Flask, render_template, request, jsonify, send_file, Response")
A("import edge_tts")
A("from openai import OpenAI")
A("")
A("try:")
A("    import fitz")
A("    PDF_SUPPORT = True")
A("except ImportError:")
A("    PDF_SUPPORT = False")
A("")
A("try:")
A("    import docx as docxlib")
A("    DOCX_SUPPORT = True")
A("except ImportError:")
A("    DOCX_SUPPORT = False")
A("")
A("try:")
A("    import wikipedia")
A("    WIKI_SUPPORT = True")
A("except ImportError:")
A("    WIKI_SUPPORT = False")
A("")
A('OPENROUTER_API_KEY = "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"')
A('openrouter_client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=OPENROUTER_API_KEY)')
A('FREE_MODELS = ["nvidia/nemotron-3-nano-30b-a3b:free"]')
A("")
A("SCRIPT_LENGTHS = {")
A('    "short":    {"exchanges": "8-10",  "words": "200-280"},')
A('    "moderate": {"exchanges": "18-22", "words": "500-600"},')
A('    "long":     {"exchanges": "32-38", "words": "900-1100"},')
A("}")
A("")
A("TONES = {")
A('    "neutral": "Natural, balanced, conversational tone.",')
A('    "formal":  "Professional, formal, structured tone. Use proper language, no slang.",')
A('    "casual":  "Super casual, friendly, relaxed tone. Use contractions, informal language.",')
A('    "comedy":  "Funny, witty, humorous tone. Add jokes, puns, light banter between hosts.",')
A('    "debate":  "Debate style - hosts disagree, challenge each other, argue different viewpoints.",')
A("}")
A("")

code = "\n".join(lines) + "\n"
open("_studio_b64.txt","w").write(base64.b64encode(code.encode()).decode())
print("part1 ok, len:", len(code))