lines = []
lines.append("import re, os, json, time, asyncio, queue, threading")
lines.append("from pathlib import Path")
lines.append("from datetime import datetime")
lines.append("from concurrent.futures import ThreadPoolExecutor, as_completed")
lines.append("from flask import Flask, render_template, request, jsonify, send_file, Response")
lines.append("import edge_tts")
lines.append("from openai import OpenAI")
lines.append("")
lines.append("try:")
lines.append("    import fitz")
lines.append("    PDF_SUPPORT = True")
lines.append("except ImportError:")
lines.append("    PDF_SUPPORT = False")
lines.append("")
lines.append("try:")
lines.append("    import docx as docxlib")
lines.append("    DOCX_SUPPORT = True")
lines.append("except ImportError:")
lines.append("    DOCX_SUPPORT = False")
lines.append("")
lines.append("try:")
lines.append("    import wikipedia")
lines.append("    WIKI_SUPPORT = True")
lines.append("except ImportError:")
lines.append("    WIKI_SUPPORT = False")
lines.append("")
KEY = "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"
lines.append(f"OPENROUTER_API_KEY = chr(34)+KEY+chr(34)")
lines.append("openrouter_client = OpenAI(base_url=" + chr(34) + "https://openrouter.ai/api/v1" + chr(34) + ", api_key=OPENROUTER_API_KEY)")
lines.append("FREE_MODELS = [" + chr(34) + "nvidia/nemotron-3-nano-30b-a3b:free" + chr(34) + "]")
open("interactive_podcast_studio.py","w",encoding="utf-8").write("\n".join(lines)+"\n")
print("ok", len(lines))
